server:
  port: 8081

spring:
  #配置spring data jpa
  jpa:
    #指定是否spring启动容器时创建表，默认fasle
    generate-ddl: true
    #指定控制台是否显示sql语句
    show-sql: true
    #指定应用重启后不自动更新表数据
    hibernate:
      ddl-auto: none
  #注册数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      test-on-borrow: true
      test-while-idle: true
    url: jdbc:mysql://localhost:3307/test?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456

  #指定微服务名称
  application:
    name: abcmsc-provider-depart
eureka:
  client:
    service-url:
      #指定当前client所要连接的 Eureka server
      defaultZone: http://localhost:8000/eureka

#region与zone -》1：n
#zone与ureka -》1：n
#复杂配置
#eureka:
#  client:
##    指定区域名称
#    region: tyh
##    指定区域中所包含的地带zone
#    availability-zones:
#      tyh: tyh01,tyh02
##      指定各个地带zone中所包含的Eureka server地址
#    service-url:
#      tyh01: http://localhost:8000/eureka
#      tyh02: http://localhost:8000/eureka
##      指定要连接的注册中心所在区域
#    fetch-remote-regions-registry: tyh

#配置日志
logging:
  #控制控制台的输出格式
  pattern:
    console: level-%level %msg%n
  #控制日志的显示级别
  level:
    #控制springboot启动时的显示日志级别
    root: info
    #控制hibernate运行时的日志级别
    org.hibernate: info
    #在show-sql为true时显示sql中的动态参数
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    #在show-sql为true时显示查询结果
    org.hibernate.type.descriptor.sql.BasicExtrator: trace
    #控制自己代码在运行时的日志级别
    com.abc.msc: debug
#    actuator
info:
  app:
    author: "tangyunahng"
    date: "2021.09.09"

#开启所有监控终端
management:
  endpoints:
    web:
      exposure:
        include: "*"
#  开启shutdown监控终端
#  endpoint:
#    shutdown:
#      enabled: true