server:
  port: 8081

spring:
  #配置spring data jpa
  jpa:
    #指定是否spring启动容器时创建表，默认fasle
    generate-ddl: true
    #指定控制台是否显示sql语句
    show-sql: true
    #指定应用重启后不自动更新表数据
    hibernate:
      ddl-auto: none
  #注册数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      test-on-borrow: true
      test-while-idle: true
    url: jdbc:mysql://localhost:3307/test?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456

#配置日志
logging:
  #控制控制台的输出格式
  pattern:
    console: level-%level %msg%n
  #控制日志的显示级别
  level:
    #控制springboot启动时的显示日志级别
    root: info
    #控制hibernate运行时的日志级别
    org.hibernate: info
    #在show-sql为true时显示sql中的动态参数
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    #在show-sql为true时显示查询结果
    org.hibernate.type.descriptor.sql.BasicExtrator: trace
    #控制自己代码在运行时的日志级别
    com.abc.msc: debug
