server:
  port: 8080
spring:
  #指定微服务名称
  application:
    name: abcmsc-consumer-depart
eureka:
  client:
    service-url:
      #指定当前client所要连接的 Eureka server
      defaultZone: http://localhost:8000/eureka
info:
  app:
    author: "tangyunahng"
    date: "2021.09.09"

#开启所有监控终端
management:
  endpoints:
    web:
      exposure:
        include: "*"
#  开启shutdown监控终端
#  endpoint:
#    shutdown:
#      enabled: true