server:
  port: 8182
spring:
  #指定微服务名称
  application:
    name: abcmsc-zuul-consumer-depart
eureka:
  client:
    service-url:
      #指定当前client所要连接的 Eureka server
      defaultZone: http://localhost:8000/eureka
  instance:
    metadata-map:
      host-mark: gray-host

info:
  app:
    author: "tangyunahng"
    date: "2021.09.09"

#开启所有监控终端
management:
  endpoints:
    web:
      exposure:
        include:  "*"
hystrix:
  dashboard:
    proxy-stream-allow-list: "localhost"

# 设置服务熔断时限
#  Feign 连接提供者、对于提供者的调用均可设置超时时限。
feign:
  client:
    config:
      default:
        commectTimeout: 5000
        readTimeout: 5000
  #  开启fegin对fallbackFactory的支持
  hystrix:
    enabled: true
