server:
  port: 8082

spring:
  #配置spring data jpa
  jpa:
    #指定是否spring启动容器时创建表，默认fasle
    generate-ddl: true
    #指定控制台是否显示sql语句
    show-sql: true
    #指定应用重启后不自动更新表数据
    hibernate:
      ddl-auto: none
  #注册数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      test-on-borrow: true
      test-while-idle: true
    url: jdbc:mysql://localhost:3307/test?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456

  #指定微服务名称
  application:
    name: abcmsc-provider-depart
eureka:
  client:
    service-url:
      #指定当前client所要连接的 Eureka server
      defaultZone: http://localhost:8000/eureka

