server:
  port: 7000
spring:
  #指定微服务名称
  application:
    name: abcmsc-hystrix-turbine
eureka:
  client:
    register-with-eureka: false #指定当前主机是否需要想Eureka Server注册自己
    fetch-registry: false #指定当前主机是否需要想Eureka Server下载注册表
    service-url:
      defaultZone: http://localhost:8000/eureka


hystrix:
  dashboard:
    proxy-stream-allow-list: "localhost"
#配置要监控的微服务名称
#turbine:
#  app-config: abcmsc-consumer-cluster1，abcmsc-consumer-cluster2
#  aggregator:
##    指定要监控的微服务组，默认default
#    cluster-config: default
##    指定要监控的微服务组名称，默认组名称为'default'
#  cluster-name-expression: "'default'"