server:
  port: 7000
spring:
  cloud:
    config:
      server:
        git:
#          指定gitee远程库地址
          uri: https://gitee.com/tangyunhang1/spring-cloud-config-server.git
#          指定连接git远程库连接超时时间，默认5秒
          timeout: 5
#          指定连接gitee远程库分支，默认master
          default-label: master
          #      配置文件所在根目录
          search-paths: config
          username: 18815292164
          password: 1Yunhang